name: whereby_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  easy_localization: ^3.0.1
  path_provider: ^2.0.11
  flutter_native_splash: ^2.2.8
  google_fonts: ^6.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^2.0.0
  hydrated_bloc: ^9.1.0
  rive: ^0.13.9
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  flutter_form_builder: ^9.1.1
  permission_handler: ^11.3.1
  flutter_parsed_text: ^2.2.1
  url_launcher: ^6.3.0
  http: ^1.2.2
  wordpress_client: ^6.3.4
  json_annotation: ^4.9.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  firebase_database: ^11.0.3
  flutter_aws_chime: ^1.1.0+1
  fluttertoast: ^8.2.8
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.0
  build_runner: ^2.2.0


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/png/
    - assets/svg/
    - assets/riv/
    - assets/locale/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
