import 'package:json_annotation/json_annotation.dart';

part 'content.g.dart'; // This will be generated by json_serializable

@JsonSerializable()
class Content {
  final String? text;
  @JsonKey(name: 'image_1')
  final String? image1;
  @JsonKey(name: 'image_2')
  final String? image2;
  final String? voiceover;
  final String? description;
  final String? image;
  final String? phrase;
  final String? example;
  final String? question;
  final String? explanation;
  final String? task;
  final String? theme;
  final List<String>? sentences;
  final List<String>? words;

  Content({
    this.text,
    this.image1,
    this.image2,
    this.voiceover,
    this.description,
    this.image,
    this.phrase,
    this.example,
    this.question,
    this.explanation,
    this.task,
    this.theme,
    this.sentences,
    this.words,
  });

  factory Content.fromJson(Map<String, dynamic> json) =>
      _$ContentFromJson(json);
  Map<String, dynamic> toJson() => _$ContentToJson(this);
}
